from datetime import date, datetime
from decimal import Decimal
from typing import Protocol
from uuid import UUID

from .domain import (
    Bank,
    BankAccount,
    LedgerEntry,
    Merchant,
    PaymentIntent,
    Person,
    Product,
    SimulationRun,
    Subscription,
)


class BankRepository(Protocol):
    def add(self, bank: Bank) -> Bank: ...

    def find_by_name(self, name: str) -> Bank | None: ...

    def status(self) -> dict: ...


class SimulationRunRepository(Protocol):
    def create(self, run: SimulationRun) -> None: ...

    def save(self, run: SimulationRun) -> None: ...

    def find(self, run_id: UUID) -> SimulationRun | None: ...

    def find_latest(self) -> SimulationRun | None: ...

    def update_status(
        self,
        run_id: UUID,
        status: str,
        error_message: str | None = None,
        hours_run: int | None = None,
    ) -> None: ...


class PersonRepository(Protocol):
    def add_people_with_accounts(
        self, people: list[Person], accounts: list[BankAccount]
    ) -> None: ...

    def count(self) -> int: ...

    def find_all(self) -> list[Person]: ...

    def find_by_id(self, person_id: UUID) -> Person | None: ...


class MerchantRepository(Protocol):
    def add(self, merchants: list[Merchant]) -> None: ...

    def count(self) -> int: ...

    def find_all(self) -> list[Merchant]: ...


class ProductRepository(Protocol):
    def add(self, products: list[Product]) -> None: ...

    def subscription_products(self) -> list[Product]: ...

    def find_all_products(self) -> list[Product]: ...

    def first_product_for_merchant(self, merchant_id) -> UUID: ...


class SubscriptionRepository(Protocol):
    def add(self, subscriptions: list[Subscription]) -> None: ...

    def count(self) -> int: ...

    def find_due_on(self, on_date: date) -> list[Subscription]: ...

    def find_all(self, limit: int = 500) -> list[Subscription]: ...

    def advance_billing_date(self, subscription_ids: list[UUID], days: int = 30) -> None: ...


class PaymentIntentRepository(Protocol):
    def add(self, intents: list[PaymentIntent]) -> None: ...

    def count(self) -> int: ...

    def find_all(self, limit: int = 500) -> list[PaymentIntent]: ...

    def find_pending(self) -> list[PaymentIntent]: ...

    def save(self, intent: PaymentIntent) -> None: ...

    def revenue_by_merchant(self) -> dict: ...

    def settled_by_merchant(self, merchant_id) -> list[PaymentIntent]: ...

    def monthly_revenue(self, merchant_id) -> list[dict]: ...


class LedgerRepository(Protocol):
    def append(self, entries: list[LedgerEntry]) -> None: ...

    def count(self) -> int: ...

    def find_recent(self, limit: int = 500) -> list[LedgerEntry]: ...

    def latest_simulation_timestamp(self) -> datetime | None: ...

    def count_by_event_type(self, event_type: str) -> int: ...

    def find_failed(self, limit: int = 200) -> list[LedgerEntry]: ...

    def balance_of(self, account_id) -> Decimal: ...

    def balances_for_accounts(self, account_ids: list) -> dict: ...
